### ISSUE TITLE
PHP Fatal error on bad username

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-betterPassword#28]
In version 1.1.0-2, enabling “Temporary account locking” and submitting a username which does not exist in the database will result in:
```
PHP Fatal error:  Uncaught TypeError: Return value of BadpwFailedLoginsDAO::getByUsername() must be an instance of BadpwFailedLogins or null, none returned in plugins/generic/betterPassword/classes/BadpwFailedLoginsDAO.inc.php:77
Stack trace:
#0 plugins/generic/betterPassword/features/LimitRetry.inc.php(95): BadpwFailedLoginsDAO->getByUsername('nosuchuser...')
#1 lib/pkp/classes/plugins/HookRegistry.inc.php(107): LimitRetry->{closure}('LoadHandler', Array)
#2 lib/pkp/classes/core/PKPPageRouter.inc.php(187): HookRegistry::call('LoadHandler', Array)
#3 lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route(Object(Request))
#4 lib/pkp/classes/core/PKPApplication.inc.php(281): Dispatcher->dispatch(Object(Request))
#5 index.php(68): PKPApplication in plugins/generic/betterPassword/classes/BadpwFailedLoginsDAO.inc.php on line 77
```

**Comment by ctgraham** [comment]
Note that the current release resolves this here:
https://github.com/ulsdevteam/pkp-betterPassword/blob/a2aa449fe4423c17b899a6896dbf9b83a47003d9/classes/BadpwFailedLoginsDAO.inc.php#L72-L75

**Comment by ctgraham** [comment]
Resolved in `stable-3_2`, no new release will be cut.
