### ISSUE TITLE
PHP Fatal error on null username

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-betterPassword#34]
In some edge cases, the `userLogin` template may not have a populated `username` template variable.

This will cause the following fatal error:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to BadpwFailedLoginsDAO::getByUsername() must be of the type string, null given, called in ojs/plugins/generic/betterPassword/features/LimitRetry.inc.php on line 55 and defined in ojs/plugins/generic/betterPassword/classes/BadpwFailedLoginsDAO.inc.php:58
Stack trace:
#0 ojs/plugins/generic/betterPassword/features/LimitRetry.inc.php(55): BadpwFailedLoginsDAO->getByUsername()
#1 ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): LimitRetry->{closure}()
#2 ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1168): HookRegistry::call()
#3 ojs/lib/pkp/pages/login/LoginHandler.inc.php(131): PKPTemplateManager->display()
#4 ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): LoginHandler->signIn()
#5 /var/www/vhosts/led in ojs/plugins/generic/betterPassword/classes/BadpwFailedLoginsDAO.inc.php
```

Source is here:
https://github.com/ulsdevteam/pkp-betterPassword/blob/193ee8c08e7a12ce5b4940e8d4125f3db08c15a9/features/LimitRetry.inc.php#L52-L58
which assumes `$username` will be a string, not null.

A grep of the source code for similar calls comes out clean.

**Comment by wopsononock** [comment]
That looks good.
