### ISSUE TITLE
Make compatible with site context

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-betterPassword#6]
Loading the settings form in 3.1.2 within a multijournal install give the following error:
```
[Wed Jul 17 13:29:07.122539 2019] [php7:notice] [pid 32120] [client 130.49.185.219:50188] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in ojs/plugins/generic/betterPassword/BetterPasswordPlugin.inc.php:122
Stack trace:
#0 ojs/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(234): betterPasswordPlugin->manage(Array, Object(Request))
#1 ojs/lib/pkp/classes/core/PKPRouter.inc.php(390): PluginGridHandler->manage(Array, Object(Request))
#2 ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#3 ojs/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPComponentRouter->route(Object(Request))
#4 ojs/lib/pkp/classes/core/PKPApplication.inc.php(252): Dispatcher->dispatch(Object(Request))
#5 ojs/index.php(68): PKPApplication->execute()
#6 {main}
  thrown in ojs/plugins/generic/betterPassword/BetterPasswordPlugin.inc.php on line 122, referer: index/admin/settings
```

**Comment by ctgraham** [comment]
Resolved in 1.0.0-1.
